<a href="https://colab.research.google.com/github/26058196-cmyk/Data-science-tutorial3/blob/main/Tutorial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Load a real dataset and visualize some of it

In [ ]:
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')

path = "/content/drive/MyDrive/StudentsPerformance.csv"
df = pd.read_csv(path)

display(df.head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

## 2. Evaluate if the data is good or not. Does it have enough samples?

In [ ]:
print("Rows and columns:", df.shape)
print("Duplicated rows:", df.duplicated().sum())

Rows and columns: (1000, 8)
Duplicated rows: 0

answer:The file contains 1000 student entries across 8 columns with zero duplicated rows. The clean format—where each row represents an individual student—simplifies processing. Having 1000 records provides a healthy balance for introductory analysis and simple regression tasks. While a deeper model might overfit due to the moderate sample size, the dataset remains fully adequate for this lab.

## 3. How many features does it have? Is it enough?

In [ ]:
print("All columns:", df.columns.tolist())
print("Total columns:", len(df.columns))

target = "math score"
features = df.drop(columns=[target])
print("Number of features:", len(features.columns))
print("Features:", features.columns.tolist())

All columns: ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']
Total columns: 8
Number of features: 7
Features: ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'reading score', 'writing score']

answer:Excluding the target variable (math score), we have 7 columns covering demographic details and other test scores. While 7 columns provide sufficient context for basic pattern detection, adding extra columns like home study time or school attendance would allow for richer insights.

## 4. How many samples / observations does it have? Is it enough?

In [ ]:
print("Number of samples (rows):", len(df))

Number of samples (rows): 1000

answer:The dataset records 1000 student observations. This volume is plenty for standard baseline evaluations, though gathering entries across different school districts would further strengthen the analysis.

## 5. What data types does the dataset consist of?

In [ ]:
print(df.dtypes)
print()
df.info()

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

**Answer:**
| Column | Python type | Type of data |
|---|---|---|
| gender | object (text) | Qualitative – nominal |
| race/ethnicity | object (text) | Qualitative – nominal (groups A–E) |
| parental level of education | object (text) | Qualitative – **ordinal** (has an order: high school → … → master's degree) |
| lunch | object (text) | Qualitative – nominal (standard / free-reduced) |
| test preparation course | object (text) | Qualitative – nominal (completed / none) |
| math score | int64 | Quantitative – discrete (whole numbers 0–100) |
| reading score | int64 | Quantitative – discrete |
| writing score | int64 | Quantitative – discrete |

It comprises 5 categorical (object) columns (ranging from nominal classifications to ordinal education ranks) and 3 numerical (int64) columns.

## 6. How many columns have null values? If yes, which columns and which rows?

In [ ]:
missing = df.isnull().sum()
print("Missing values in each column:")
print(missing)
print()
print("Number of columns with missing values:", (missing > 0).sum())

Missing values in each column:
gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

Number of columns with missing values: 0

answer:All columns report 0 null values, so no specific columns or rows need to be flagged for missing data.

## 7. Which column is the feature, which is the target output?

In [ ]:
print("Target:", target)
print("Features:", features.columns.tolist())
print("Unique values of the target (first 10):", sorted(df[target].unique().tolist())[:10])

Target: math score
Features: ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'reading score', 'writing score']
Unique values of the target (first 10): [0, 8, 18, 19, 22, 23, 24, 26, 27, 28]

answer:The main target is math score, while the remaining 7 columns serve as predictive features. Because no student personal identifiers (like student IDs) are included, no extra column removal is needed.

## 8. Does it have missing values? If yes, which column, which row

In [ ]:
rows_missing = df[df.isnull().any(axis=1)]
print("Number of rows with missing values:", len(rows_missing))
display(rows_missing.head(10))

Number of rows with missing values: 0

Empty DataFrame
Columns: [gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score]
Index: []

answer:No. All 1000 rows are completely filled with data. Since missing value handling isn't required, preprocessing this dataset is very straightforward.

## 9. What kind of questions can be asked? Does the dataset suit the question we are asking?
Questions

1.Do female and male students show different score distributions across the three subjects?

2.Is there a strong link between reading and writing scores?

3.Does a higher level of parental education correspond to better test outcomes?

answer:The dataset fits these questions well because it holds balanced academic records for 1000 students with zero missing values. However, since it only shows statistical relationships (correlation) rather than direct cause-and-effect, we cannot conclude that one factor directly causes higher test scores.